// SPDX-License-Identifier: MIT
/**
 * `/export` — write a team config YAML from the database (SPEC §5, export side).
 *
 * The database is the source of truth; a config file is an export artifact
 * (D3). Everything this module emits is decided by `metadata-taxonomy.ts`:
 *
 *   - The COLUMN list is DERIVED from `classifyAgentColumn`, never `SELECT *`
 *     and never "all columns except". A column added to the schema later is
 *     `unknown` and is not exported until someone classifies it on purpose.
 *   - METADATA keys go through `classifyMetadataKey`. `config` and `identifier`
 *     are written; `runtime` and `derived` are dropped silently because they
 *     are reproducible; `unknown` is dropped and REPORTED (§3.1 rule 1),
 *     because silent omission is a data-loss bug.
 *
 * Out of scope here, by design: auto-export (§5.4, commit 3), import (§5.2.3 /
 * §7, commit 7), `/diff` (§8).
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

import {
  classifyAgentColumn,
  classifyMetadataKey,
  listClassifiedColumns,
} from './metadata-taxonomy.js';

/**
 * §5.6 — REQUIRED in every export result, in the JSON body AND the
 * human-readable output. Export is not a complete backup, and anyone treating
 * it as disaster recovery needs to know the limit before they need the backup.
 */
export const WALLET_EXPORT_WARNING =
  'Wallets are not exported. Imported agents provision new wallets; the originals ' +
  'remain in the OWS vault and are not reachable from the restored team.';

/**
 * Avatar rules (§5.2.2).
 *
 * NOTE: the spec cites `ProfileService.ts` for these constants, but that file
 * lives in the desktop repo — core has no avatar code at all. They are
 * duplicated here deliberately and must be kept in sync with it; if the two
 * ever disagree, export will silently diverge from what the writer accepts.
 */
export const AVATAR_EXTS = ['png', 'jpg', 'jpeg', 'webp'] as const;
export const MAX_AVATAR_BYTES = 5 * 1024 * 1024;
/** Matches ProfileService's path-segment guard. */
export const SAFE_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

export interface AgentRowLike {
  name: string;
  metadata?: Record<string, unknown> | null;
  [column: string]: unknown;
}

/**
 * Is this `working_directory` a path the DEPLOYER synthesised, or one the AUTHOR
 * chose? (#f37ad05d)
 *
 * Deploy writes `<baseWorkDir>/agents/<agentId>` when a config carries no
 * `workingDirectory` (`agent-manager-db.ts:6122-6124`). Exporting that value
 * back verbatim points a RESTORED agent — which gets a NEW id under create-only
 * deploy — at the ORIGINAL agent's live directory.
 *
 * The rule this encodes: *a path the deployer synthesised is not a fact about
 * the team; a path the author chose is.*
 *
 * THE TEST IS EXACT, AND DELIBERATELY SO. Live data is 43 authored / 4
 * generated / 0 ambiguous, and the two failure directions are wildly asymmetric:
 * missing a generated path leaves today's bug in place, while a false positive
 * on an AUTHORED path (`/Users/nxt3d/projects/idx`, `id2/id-app`,
 * `idx-gateway`) silently restores a team into an empty scratch directory. A
 * prefix or `startsWith` match would do exactly that to any team whose author
 * chose a path inside baseWorkDir. So: full-string equality, and anything that
 * does not match to the byte is treated as authored and emitted untouched.
 *
 * Without a `baseWorkDir` there is nothing to compare against, so every path is
 * authored — the safe direction.
 */
export function isGeneratedWorkdir(row: AgentRowLike, baseWorkDir?: string): boolean {
  if (!baseWorkDir) return false;
  const workdir = row.working_directory;
  const id = row.id;
  if (typeof workdir !== 'string' || !workdir) return false;
  if (typeof id !== 'string' || !id) return false;
  return workdir === path.join(baseWorkDir, 'agents', id);
}

/**
 * The comment that replaces a generated `workingDirectory` (wording approved by
 * Prem; keep it close to verbatim).
 *
 * An exported config is a SNAPSHOT A HUMAN READS AND ADJUSTS, not a push-button
 * restore artifact. So the path's INFORMATION survives and its VALUE does not:
 * as a comment it still tells an operator where the agent's files are, but it
 * can never reach `mkdirSync`.
 *
 * The closing clause is load-bearing. Naming the concrete consequence — two
 * agents sharing one directory — is what stops someone pasting the path back in
 * as a value, which would reintroduce the exact bug this fixes.
 */
export function generatedWorkdirComment(workdir: string, indent = ''): string {
  return [
    `${indent}# workingDirectory was generated by the deployer, not chosen — omitted so import`,
    `${indent}# creates a fresh one for the new agent id. At export time this agent worked in:`,
    `${indent}#   ${workdir}`,
    `${indent}# That directory belongs to the ORIGINAL agent and is probably still live. Read it`,
    `${indent}# if you need its files; do not paste it back as a value, or two agents will share one.`,
  ].join('\n');
}

export interface ScheduleLike {
  kind: string;
  active: boolean;
  interval_seconds: number | null;
}

export interface ExportResult {
  ok: true;
  path: string;
  agents: number;
  /** Unknown/unclassified metadata keys per agent (§3.1 rule 1). */
  skipped: Array<{ agent: string; keys: string[] }>;
  warnings: string[];
}

/** Column name -> config field name. Renames only; membership is the taxonomy's call. */
export const COLUMN_CONFIG_KEY: Readonly<Record<string, string>> = Object.freeze({
  name: 'name',
  type: 'type',
  model: 'model',
  runtime: 'runtime',
  working_directory: 'workingDirectory',
  customer_domain: 'customer_domain',
  public_endpoint_url: 'public_endpoint_url',
  token_id: 'tokenId',
  domain: 'domain',
});

/** Metadata key -> config field name, where the two differ. */
const METADATA_CONFIG_KEY: Readonly<Record<string, string>> = Object.freeze({
  allowed_tools: 'allowedTools',
});

/**
 * The exported column allow-list, derived from the taxonomy at call time.
 *
 * This is the §5.3 / acceptance-5a requirement in one function: membership is
 * decided by `classifyAgentColumn`, so `api_key`, `ssh_target` and
 * `internal_endpoint_url` (class `never`) can never appear, and neither can a
 * column nobody has classified.
 *
 * `classify` is injectable ONLY so the taxonomy gate can be tested. Today it and
 * `COLUMN_CONFIG_KEY` cover exactly the same nine columns, so with the real
 * classifier the gate is unobservable — remove it and every output-level
 * assertion still passes. The seam lets a test demote a column and prove the
 * gate, not the rename map, is what drops it.
 */
export function exportedColumns(
  classify: (column: string) => string = classifyAgentColumn,
): string[] {
  return listClassifiedColumns()
    .filter((column) => {
      const klass = classify(column);
      return klass === 'config' || klass === 'identifier';
    })
    .filter((column) => Object.prototype.hasOwnProperty.call(COLUMN_CONFIG_KEY, column));
}

/**
 * Build one `agents[]` entry, plus the unknown keys it had to drop.
 *
 * The agent's exported name is `metadata.alias || name` — the shipped
 * DB→config precedent at `interactive-agent-cli.ts:967`. `alias` itself stays
 * unclassified, so it is dropped and reported like any other unknown key.
 */
export function buildAgentEntry(
  row: AgentRowLike,
  schedules: ScheduleLike[] = [],
  baseWorkDir?: string,
): { entry: Record<string, unknown>; skippedKeys: string[]; generatedWorkdir?: string } {
  const entry: Record<string, unknown> = {};
  const skippedKeys: string[] = [];

  // #f37ad05d: a deployer-generated path is carried out as a COMMENT, so the
  // key must never be written. Import then regenerates for the new agent id.
  const generated = isGeneratedWorkdir(row, baseWorkDir);
  const generatedWorkdir = generated ? String(row.working_directory) : undefined;

  for (const column of exportedColumns()) {
    if (generated && column === 'working_directory') continue;
    const value = row[column];
    if (value === undefined || value === null || value === '') continue;
    entry[COLUMN_CONFIG_KEY[column]] = value;
  }

  const metadata = (row.metadata || {}) as Record<string, unknown>;
  for (const key of Object.keys(metadata)) {
    const value = metadata[key];
    switch (classifyMetadataKey(key)) {
      case 'config':
      case 'identifier':
        if (value !== undefined && value !== null) {
          entry[METADATA_CONFIG_KEY[key] || key] = value;
        }
        break;
      case 'runtime':
      case 'derived':
        break; // reproducible, never written (§5.3)
      case 'unknown':
        skippedKeys.push(key); // dropped, but never silently (§3.1 rule 1)
        break;
    }
  }

  // The exported name folds in the alias; see interactive-agent-cli.ts:967.
  const alias = metadata.alias;
  if (typeof alias === 'string' && alias) entry.name = alias;

  // §3.1 rule 4: metadata.heartbeat is a boolean. The interval lives in the
  // schedules table, so reconstruct it rather than exporting the flag.
  if (entry.heartbeat !== undefined) {
    const beat = schedules.find((s) => s.kind === 'heartbeat' && s.active);
    if (beat?.interval_seconds) entry.heartbeat = beat.interval_seconds;
    else delete entry.heartbeat;
  }

  return { entry, skippedKeys, generatedWorkdir };
}

/**
 * Can this row be written into a config file at all?
 *
 * `type: 'claude'` and `'automator'` are both declarable in `AgentSpec`, and a
 * `public-agent-remote` row carries `customer_domain` / `public_endpoint_url`,
 * which are too. Everything else — the `interactive` and `virtual` rows that
 * `POST /agents/register` creates — has no config representation: there is no
 * YAML that reproduces an externally-registered agent.
 *
 * Those rows must still be ACCOUNTED FOR. §3.1 rule 1 says an unknown metadata
 * key is reported rather than dropped; the same rule has to hold one level up,
 * or an entire agent disappears from an export with nothing said. That is
 * exactly what happened to `default/cto` before this existed.
 */
export function isConfigExpressible(row: AgentRowLike): boolean {
  const type = typeof row.type === 'string' ? row.type : '';
  if (type !== 'interactive' && type !== 'virtual') return true;
  return row.runtime === 'public-agent-remote';
}

/** Assemble the full team config document. `defaults` holds only unanimous values. */
export function buildTeamConfig(
  teamName: string,
  agents: AgentRowLike[],
  schedulesByAgent: Record<string, ScheduleLike[]> = {},
  org?: unknown,
  baseWorkDir?: string,
): {
  config: Record<string, unknown>;
  skipped: ExportResult['skipped'];
  unrepresentable: Array<{ agent: string; type: string; runtime: string }>;
  /** Agents whose generated workdir must be emitted as a comment (#f37ad05d). */
  generatedWorkdirs: Array<{ agent: string; path: string }>;
} {
  const skipped: ExportResult['skipped'] = [];
  const unrepresentable: Array<{ agent: string; type: string; runtime: string }> = [];
  const generatedWorkdirs: Array<{ agent: string; path: string }> = [];

  const exportable = agents.filter((row) => {
    if (isConfigExpressible(row)) return true;
    unrepresentable.push({
      agent: String(row.name),
      type: String(row.type ?? 'unknown'),
      runtime: String(row.runtime ?? 'unknown'),
    });
    // Still walk the metadata: naming the keys that have no home anywhere is
    // more useful to an operator than "this agent was skipped".
    const { skippedKeys } = buildAgentEntry(row, []);
    if (skippedKeys.length) skipped.push({ agent: String(row.name), keys: skippedKeys });
    return false;
  });

  const entries = exportable.map((row) => {
    const { entry, skippedKeys, generatedWorkdir } = buildAgentEntry(
      row,
      schedulesByAgent[String(row.name)] || [],
      baseWorkDir,
    );
    if (skippedKeys.length) skipped.push({ agent: String(entry.name ?? row.name), keys: skippedKeys });
    // Keyed by the EXPORTED name (alias folded in), because that is the name
    // the comment has to be anchored against in the dumped YAML.
    if (generatedWorkdir) {
      generatedWorkdirs.push({ agent: String(entry.name ?? row.name), path: generatedWorkdir });
    }
    return entry;
  });

  // §5.2: `defaults` carries a field only where every agent agrees on it.
  const defaults: Record<string, unknown> = {};
  for (const field of ['runtime', 'model', 'type'] as const) {
    const values = entries.map((e) => e[field]);
    if (values.length > 1 && values.every((v) => v !== undefined && v === values[0])) {
      defaults[field] = values[0];
      for (const e of entries) delete e[field];
    }
  }

  const config: Record<string, unknown> = { version: '1', team: teamName };
  if (Object.keys(defaults).length) config.defaults = defaults;
  if (org !== undefined && org !== null) config.org = org;
  config.agents = entries;
  return { config, skipped, unrepresentable, generatedWorkdirs };
}

/**
 * Insert each generated-workdir comment above its agent entry (#f37ad05d).
 *
 * POST-PROCESSING THE DUMPED STRING IS DELIBERATE. `js-yaml`'s `dump()` cannot
 * attach a comment to a node — the two header lines this module already writes
 * work only because they are prepended to the whole document. Swapping the
 * serializer for one that can (e.g. `yaml`) would reformat every exported file,
 * which is not worth it for five comment lines.
 *
 * Anchoring on `- name: <agent>`: `name` is the first key of every entry
 * (`COLUMN_TAXONOMY` order), so it carries the sequence dash, and names are
 * unique within a file.
 *
 * A MISS IS REPORTED, NEVER SWALLOWED. The key has already been dropped by the
 * time this runs, so a silently-failed insertion would lose the path entirely —
 * the precise silent-data-loss failure this whole build exists to stop.
 */
export function insertWorkdirComments(
  dumped: string,
  generatedWorkdirs: Array<{ agent: string; path: string }>,
): { text: string; missing: string[] } {
  const missing: string[] = [];
  let text = dumped;

  for (const { agent, path: workdir } of generatedWorkdirs) {
    // The name may be quoted by the dumper; tolerate either form.
    const escaped = agent.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const anchor = new RegExp(`^([ \\t]*)-([ \\t]+)name:[ \\t]*(['"]?)${escaped}\\3[ \\t]*$`, 'm');
    const match = anchor.exec(text);
    if (!match) {
      missing.push(agent);
      continue;
    }
    const indent = match[1];
    const comment = generatedWorkdirComment(workdir, indent);
    text = `${text.slice(0, match.index)}${comment}\n${text.slice(match.index)}`;
  }

  return { text, missing };
}

/**
 * Mirror avatars into `configs/avatars/<team>/<agent>/avatar.<ext>` (§5.2.1).
 *
 * Root swap only. Selects `avatar.*` EXPLICITLY rather than sweeping the
 * directory, so the `.DS_Store` that exists beside a live avatar today is
 * never copied, and re-validates size because export does not trust what is
 * already on disk (§5.2.2 rule 3).
 */
export function exportAvatars(
  teamName: string,
  agentNames: string[],
  profilesRoot: string,
  avatarsRoot: string,
): { copied: string[]; warnings: string[] } {
  const copied: string[] = [];
  const warnings: string[] = [];
  if (!SAFE_SEGMENT.test(teamName)) {
    warnings.push(`Avatar export skipped for team "${teamName}": unsafe team name.`);
    return { copied, warnings };
  }

  for (const agentName of agentNames) {
    if (!SAFE_SEGMENT.test(agentName)) {
      warnings.push(`Avatar skipped for "${agentName}": name fails the safe-segment guard.`);
      continue;
    }
    const sourceDir = path.join(profilesRoot, teamName, agentName);
    for (const ext of AVATAR_EXTS) {
      const source = path.join(sourceDir, `avatar.${ext}`);
      let stat: fs.Stats;
      try {
        stat = fs.statSync(source);
      } catch {
        continue; // no avatar with this extension
      }
      if (!stat.isFile()) continue;
      if (stat.size > MAX_AVATAR_BYTES) {
        warnings.push(
          `Avatar skipped for "${agentName}": ${stat.size} bytes exceeds the ${MAX_AVATAR_BYTES}-byte limit.`,
        );
        continue;
      }
      const destDir = path.join(avatarsRoot, teamName, agentName);
      try {
        fs.mkdirSync(destDir, { recursive: true });
        fs.copyFileSync(source, path.join(destDir, `avatar.${ext}`));
        copied.push(path.join(destDir, `avatar.${ext}`));
      } catch (err: unknown) {
        warnings.push(`Avatar skipped for "${agentName}": ${(err as Error)?.message || String(err)}`);
      }
    }
  }
  return { copied, warnings };
}

/**
 * §5.1 default path: an explicit argument wins, else the team's recorded
 * `last_config_path`, else `<baseWorkDir>/teams/<team>/<team>.yaml`.
 *
 * Kept here rather than in the command handler so the precedence is testable
 * without standing up a manager, and so there is exactly one implementation of
 * it when auto-export (§5.4) needs the same fallback with a different filename.
 */
export function resolveExportPath(
  explicitPath: string | undefined,
  lastConfigPath: unknown,
  baseWorkDir: string,
  teamName: string,
): string {
  if (typeof explicitPath === 'string' && explicitPath.trim()) return explicitPath.trim();
  if (typeof lastConfigPath === 'string' && lastConfigPath.trim()) return lastConfigPath.trim();
  return path.join(baseWorkDir, 'teams', teamName, `${teamName}.yaml`);
}

export interface ExportOptions {
  teamName: string;
  agents: AgentRowLike[];
  targetPath: string;
  schedulesByAgent?: Record<string, ScheduleLike[]>;
  org?: unknown;
  profilesRoot?: string;
  avatarsRoot?: string;
  /**
   * The manager's base working directory, used ONLY to tell a deployer-generated
   * `working_directory` from an authored one (#f37ad05d). Omitted: every path is
   * treated as authored and emitted as-is — the pre-existing behaviour.
   */
  baseWorkDir?: string;
}

/** Write the team config YAML, backing up any existing file first (§5.1). */
export function exportTeamConfig(options: ExportOptions): ExportResult {
  const { teamName, agents, targetPath, schedulesByAgent = {}, org, baseWorkDir } = options;
  const { config, skipped, unrepresentable, generatedWorkdirs } =
    buildTeamConfig(teamName, agents, schedulesByAgent, org, baseWorkDir);

  const warnings: string[] = [WALLET_EXPORT_WARNING];
  // Every row the config cannot represent is named here. An agent silently
  // missing from an export is the worst failure this command has, because the
  // file looks complete.
  for (const row of unrepresentable) {
    warnings.push(
      `Agent "${row.agent}" (type=${row.type}, runtime=${row.runtime}) was NOT exported: ` +
      `externally-registered agents have no config representation. Re-register it after import.`,
    );
  }
  if (options.profilesRoot && options.avatarsRoot) {
    const avatars = exportAvatars(
      teamName,
      agents.map((a) => String(a.name)),
      options.profilesRoot,
      options.avatarsRoot,
    );
    warnings.push(...avatars.warnings);
  }

  const { text: body, missing } = insertWorkdirComments(
    yaml.dump(config, { noRefs: true, lineWidth: 120 }),
    generatedWorkdirs,
  );
  for (const agent of missing) {
    warnings.push(
      `Agent "${agent}" had a deployer-generated workingDirectory, but the comment could not be ` +
      `anchored in the output — the path is NOT recorded in this file. Report this; it is a bug.`,
    );
  }

  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  if (fs.existsSync(targetPath)) fs.copyFileSync(targetPath, `${targetPath}.bak`);
  fs.writeFileSync(
    targetPath,
    `# Exported from the database by /export — the database is the source of truth.\n` +
      `# ${WALLET_EXPORT_WARNING}\n` +
      body,
  );

  // `agents` counts what was WRITTEN; unrepresentable rows are in `warnings`.
  // exported + reported === rows handed in, which is the completeness contract.
  const exportedCount = agents.length - unrepresentable.length;
  return { ok: true, path: targetPath, agents: exportedCount, skipped, warnings };
}

/** Human-readable output. §5.6 requires the warning here too, not only in JSON. */
export function formatExportResult(result: ExportResult): string {
  const lines = [`Exported ${result.agents} agent(s) to ${result.path}`];
  for (const { agent, keys } of result.skipped) {
    lines.push(`  skipped unknown key(s) on ${agent}: ${keys.join(', ')}`);
  }
  for (const warning of result.warnings) lines.push(`  warning: ${warning}`);
  return lines.join('\n');
}
